# Image configuration
image:
  repository: layzer/sealos-procscan
  pullPolicy: Always
  tag: "v0.0.2-alpha-6"

# Namespace
namespace: sealos

# ServiceAccount configuration
serviceAccount:
  create: true
  name: process-scanner
  automountServiceAccountToken: true

# RBAC configuration
rbac:
  create: true
  clusterRole:
    name: process-scanner
  clusterRoleBinding:
    name: process-scanner

# DaemonSet configuration
daemonset:
  name: proc-scan
  labels:
    app: proc-scan
    version: v1.0.0
  podLabels:
    app: process-scanner
    version: v1.0.0

  # Host network and PID
  hostNetwork: false
  hostPID: true

  # Pod security context
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
    supplementalGroups:
      - 0

  # Security context
  securityContext:
    privileged: false
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 65532
    runAsGroup: 65532
    capabilities:
      drop:
        - ALL
      add:
        - SYS_PTRACE
        - DAC_READ_SEARCH

  # Resource limits
  resources:
    limits:
      memory: 512Mi
      cpu: 500m
    requests:
      memory: 64Mi
      cpu: 50m

# Configuration file
config:
  scanner:
    proc_path: "/host/proc"
    scan_interval: "100s"
    log_level: "info"

  actions:
    label:
      enabled: false
      data:
        clawcloud.run/status: "locked"

  notifications:
    lark:
      webhook: ""

  detectionRules:
    blacklist:
      processes:
        - "^miner$"
        - "agsb"
        - "xmrig"
      keywords:
        - "xmr.pool.gulf.obtc.com"
    whitelist:
      processes:
        - "legit-process"
      commands:
        - "/usr/bin/bash -c 'legit-script'"
      namespaces:
        - "ns-dev-test"
      podNames:
        - "special-debug-pod-"

volumes:
  proc:
    hostPath: /proc
    mountPath: /host/proc
  containerdSock:
    hostPath: /var/run/containerd/containerd.sock
    mountPath: /var/run/containerd/containerd.sock
  config:
    mountPath: /config
