version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/complik"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/block-controller"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/procscan"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/analyze"
    schedule:
      interval: "daily"